package gregtech.common.metatileentities.multi.electric.godforge.module;

import gregtech.api.metatileentity.MetaTileEntity;
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity;
import gregtech.api.pattern.element.Elements;
import gregtech.api.pattern.element.IStructureElement;
import gregtech.api.recipes.GodforgeRecipeMaps;
import gregtech.api.recipes.Recipe;
import gregtech.api.recipes.properties.impl.TemperatureProperty;
import gregtech.common.blocks.BlockGodforgeCasing;
import gregtech.common.mui.multiblock.godforge.MTEBaseModuleGui;
import gregtech.common.mui.multiblock.godforge.MTEMoltenModuleGui;

import net.minecraft.util.ResourceLocation;

import org.jetbrains.annotations.NotNull;

/**
 * Godforge Molten Module. Converts blast furnace inputs directly into their molten fluid outputs. Temperature check
 * applies — only recipes within the module's heat capability are matched. Recipes are auto-generated by
 * {@code GodforgeRecipeLoader} from BLAST_RECIPES.
 */
public class MTEMoltenModule extends MTEBaseModule {

    public MTEMoltenModule(ResourceLocation metaTileEntityId) {
        super(metaTileEntityId, GodforgeRecipeMaps.GODFORGE_MOLTEN_RECIPES);
    }

    @Override
    public MetaTileEntity createMetaTileEntity(IGregTechTileEntity tileEntity) {
        return new MTEMoltenModule(metaTileEntityId);
    }

    @Override
    protected MTEBaseModuleGui<?> createModuleGui() {
        return new MTEMoltenModuleGui(this);
    }

    @Override
    protected IStructureElement getCoilBlockElement() {
        return Elements.block(getCasingState(
                BlockGodforgeCasing.CasingType.TRANSCENDENTALLY_AMPLIFIED_MAGNETIC_CONFINEMENT_CASING));
    }

    @Override
    public boolean checkRecipe(@NotNull Recipe recipe, boolean consumeIfSuccess) {
        int recipeTemp = recipe.getProperty(TemperatureProperty.getInstance(), 0);
        return getHeat() >= recipeTemp;
    }
}
