package gregtech.api.items.toolitem;

public enum ToolOreDict {
    toolSword,
    toolPickaxe,
    toolShovel,
    toolAxe,
    toolHoe,
    toolSaw,
    toolHammer,
    toolMallet,
    toolMiningHammer,
    toolSpade,
    toolWrench,
    toolFile,
    toolCrowbar,
    toolScrewdriver,
    toolMortar,
    toolWireCutter,
    toolHammerDrill,
    toolScythe,
    toolKnife,
    toolShears,
    toolButcheryKnife,
    toolClub,
    toolDrill,
    toolChainsaw,
    toolBuzzsaw,
    toolFlintAndSteel,
    toolPincers,
    toolBendingCylinder,
    toolBendingCylinderSmall,
    toolPlunger
}
